#import "template.typ": item

// Chapter 2 is split across two foldable sheets (9 parts don't fit one half-page).

#let ch2a = (
  chapter: "2",
  title: "Requirements Engineering",
  part: "Part 1 of 2 (a–e)",
  tag: "2.6",
  slide: 270,
  items: (
    item("a", 2,
      [Define the security attribute “Availability”.],
      [*Availability* is *ensuring timely and reliable access to and use of information* — i.e. *preventing absences and downtimes*. Exemplary means: defining a maximum amount of resource requests (cloud scaling) and having *backup and recovery plans*.],
      graded: [timely + reliable access/use of information; preventing downtime.],
      cite: "216, 213"),
    item("b", 2,
      [Define the security attribute “Integrity” for data and systems.],
      [*Integrity* means *guarding against improper modification or destruction* of information, and includes ensuring *non-repudiation* and *authenticity*. It *prevents unintentional alterations*; means include defining who may change what and using *checksums / digital signatures* to detect changes.],
      graded: [guarding against improper/unintended modification or destruction; includes non-repudiation + authenticity.],
      cite: "215, 213"),
    item("c", 1,
      [Give an example of the security principle “Economy of mechanism”.],
      [*Hardware security modules (HSMs)*, or *Let's Encrypt* SSL certificates — keeping the design as simple and small as possible (Optional)(, because they are easier to audit and to integrate).],
      graded: [one valid example (HSMs or Let's Encrypt).],
      cite: "234"),
    item("d", 1,
      [Give an example of the security principle “Defense in depth”.],
      [*Two-factor authentication / TANs* for sensitive actions, or *firewalls plus demilitarized zones* — multiple independent layers of defense.],
      graded: [one valid example (2FA/TAN or firewall + DMZ).],
      cite: "256"),
    item("e", 2,
      [Define the security principle “Least Common Mechanism”.],
      [*Minimize artifacts shared among different applications and users.* Rationale: a single vulnerability then *affects only a single application/user*, and diversity complicates large-scale attacks (e.g. a different key per permission within a session).],
      graded: [minimize shared artifacts/mechanisms between users/apps; limits blast radius of one flaw.],
      cite: "246"),
  ),
)

#let ch2b = (
  chapter: "2",
  title: "Requirements Engineering",
  part: "Part 2 of 2 (f–i)",
  tag: "2.6",
  slide: 270,
  items: (
    item("f", 2,
      [Define the security principle “Psychological Acceptability”.],
      [*Match the security mechanism to the user's mental image.* Rationale: we want users to actually *use and prefer secure systems*; otherwise legitimate users *work around* the security measures to get their task done.],
      graded: [fit mechanism to user's mental model; else users circumvent it.],
      cite: "248"),
    item("g", 2,
      [Name one argument for and one argument against the application of the security principle “Open Design”.],
      [*Open Design* = share implementation details with others, even the attacker. *For:* it enables *reviews and white-box analyses* and re-use of designs (cf. *Kerckhoffs*: a cipher should not require secrecy; *Linus' Law*: “given enough eyeballs, all bugs are shallow”). *Against:* the “many eyeballs” claim is contested — Glass lists it as *Fallacy 8*, and bugs can survive long in popular open code (e.g. *Heartbleed* in OpenSSL: introduced 2012, found 2014).],
      graded: [one pro (review/white-box, Kerckhoffs/Linus' Law) + one con (eyeballs fallacy / Heartbleed longevity).],
      cite: "240, 264, 265"),
    item("h", 3,
      [Is it possible to satisfy the security attribute “Non-repudiation” without “Accountability” in the same activity? Justify your answer using the definitions of the two terms.],
      [*No.* *Non-repudiation* protects against an individual *falsely denying having performed a particular action*, i.e. one must be able to *determine whether a given individual took that action*. *Accountability* is the property of *being able to trace activities to the individuals* responsible. Determining that a specific person did the action (non-repudiation) already *requires tracing the action to that individual* — which is exactly accountability. So non-repudiation *presupposes* accountability and cannot be satisfied without it in the same activity.],
      graded: [No + reasoning: non-repudiation requires attributing the action to a specific individual, which is what accountability provides, so it presupposes accountability.],
      cite: "224, 223"),
    item("i", 3,
      [Is it possible to satisfy both the security attribute “Privacy” and “Anonymity” for the same data at the same time? Justify your answer using the definitions of the two terms.],
      [*Yes.* *Privacy* is a party's *right to keep control over and confidentiality of information about itself*; *Anonymity* is the condition that an entity *can be recognized as distinct without enough identity information to link it to a known identity*. They target different aspects and are *complementary*: anonymity removes the *link* to the real identity, while privacy *controls/protects* the data that does exist. Concealing the identity link does not conflict with controlling the data — both can hold at once (e.g. published *grade averages only*, with strict retention limits).],
      graded: [Yes + reasoning: anonymity hides the identity link, privacy controls/protects the data; different aspects, complementary, not mutually exclusive.],
      cite: "218, 219"),
  ),
)
